[Params]

  # Status da barra de navegacao ↓
  [Params.Navbar]
  use = true
  
  # Extensoes ↓
  [Params.Extensions]
  use = true
  ext = ".txt"    

 
  # Tema do terminal ↓
  [Params.Terminal]
  scheme = "Nord"

  # Nomenclatura ↓
  userName = "johnnyhall"
  pcName = "pop-os"
  workDir = "mydir"
  profile = "profile.txt"


  # Velocidade dos comandos ↓
  ps1Delay = 0 
  stdoutDelay = 0 
  commandDelay = 50


  # Decricao ↓
  description = """
  Hello my name is Joao Tapparo
  Welcome to my blog!!
  """


  # Parametros do comando Tree ↓
  [Params.Tree]
  use = true
  folderName = "my_activity"
  files = [ 
    ["posts", "/post"],
    ["projects", "https://www.example.com/"],
    ["about me", "https://golang.org/"],
  ]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.85.0"
